### ISSUE TITLE
Bluetooth Timeout for E4

### ISSUE THREAD

**Issue by zulqarnain343** [RADAR-base/radar-prmt-inhospital-deploy#1] opened 2018-03-22 10:50 UTC
App stops the Bluetooth connection for E4 periodically (more or less twice in an hour) and asks for permission. 

![prmt app bluetooth timeout](https://user-images.githubusercontent.com/33095752/37765639-95c7c2ca-2dbc-11e8-812c-1b59f5da0353.png)

**Comment by sboettcher** [comment] 2018-03-22 14:37
Can confirm, likely a duplicate of this issue https://github.com/RADAR-base/radar-prmt-android/issues/53.
It has been happening from the start and I think it is not caused by Empatica, but am also not 100% sure about that.
In any case it is probably better to reopen that issue there and see if we can't fix it somehow.

**Comment by afolarin** [comment] 2021-09-23 13:48
closing for archiving.

**Closed as completed by afolarin** 2021-09-23 13:48 UTC
